name: Generate and Sign SBOM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE=myapp:latest
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Generate SBOM (Trivy)
        uses: aquasecurity/trivy-action@60c57ad5ad7f270cecb51dff2dbf4d680114f6f8 # 0.67.2
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE }}
          format: spdx-json
          output: sbom.spdx.json

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Check install
        run: cosign version

      - name: Sign Docker image (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --keyless $IMAGE

      - name: Sign SBOM file (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign-blob --keyless sbom.spdx.json