name: Generate and Sign SBOM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup Docker Buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Github Container Registry
      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push image â€” output digest
      - name: Build and push image by digest
        id: build-digest
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sbomdemo:${{ github.sha }}
 
      # Generate SBOM and Upload to Github Dependecy Graph (Trivy)
      - name: Generate SBOM and Submit to Dependecy Graph
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository_owner }}/sbomdemo@${{ steps.build-digest.outputs.digest }}
          format: "cyclonedx"
          output: "sbom.cyclonedx.json"
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      # Install Cosign
      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      # Sign container image (SHA digest)
      - name: Sign image by digest
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes \
          ghcr.io/${{ github.repository_owner }}/sbomdemo@${{ steps.build-digest.outputs.digest }}
      
      # Verify image signature
      - name: Verify image signature
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify \
            ghcr.io/${{ github.repository_owner }}/sbomdemo@${{ steps.build-digest.outputs.digest }} \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity-regexp "^https://github.com/${{ github.repository }}/\.github/workflows/.*@refs/.*$"

      # Sign SBOM
      - name: Sign CycloneDX SBOM
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign-blob --yes sbom.cyclonedx.json \
            --bundle sbom.cyclonedx.signed.json

      # Verify SBOM signature
      - name: Verify SBOM signature
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify-blob \
            sbom.cyclonedx.json \
            --bundle sbom.cyclonedx.signed.json \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity-regexp "^https://github.com/${{ github.repository }}/\.github/workflows/.*@refs/.*$"
        
      # Upload SBOM + signature
      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: |
            sbom.cyclonedx.json
            sbom.cyclonedx.signed.json